# Generated by Django 4.2.7 on 2023-11-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('record_date', models.DateField()),
                ('workshop', models.CharField(choices=[('DpR-Csp-uipv-ShV-V1', 'DpR-Csp-uipv-ShV-V1'), ('Pgp-com2-K-1-0-9-36', 'Pgp-com2-K-1-0-9-36'), ('Pgp-lpc2-K-0-1-38', 'Pgp-lpc2-K-0-1-38'), ('Phl-com3-Shv2-9-K34', 'Phl-com3-Shv2-9-K34'), ('Php-Angc-K3-1', 'Php-Angc-K3-1'), ('Php-Angc-K3-8', 'Php-Angc-K3-8'), ('Php-Ctm-K-1-12-56', 'Php-Ctm-K-1-12-56'), ('Php-Ctm-Shv1-2-K3', 'Php-Ctm-Shv1-2-K3'), ('Php-nta4-shv016309-k2-1-7', 'Php-nta4-shv016309-k2-1-7'), ('Spp-210-K1-3-3-5', 'Spp-210-K1-3-3-5'), ('Spp-210-K1-3-3-6', 'Spp-210-K1-3-3-6'), ('Spp-K1-1-2-6_zone1', 'Spp-K1-1-2-6_zone1'), ('Spp-K1-1-2-6_zone2', 'Spp-K1-1-2-6_zone2'), ('Spp-K1-1-2-6_zone3', 'Spp-K1-1-2-6_zone3'), ('Spp-K1-1-2-6_zone4', 'Spp-K1-1-2-6_zone4')], max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('detected_image', models.ImageField(blank=True, upload_to='detected_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='signal_record',
            name='video',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='signal_record',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.image'),
            preserve_default=False,
        ),
    ]
