# Generated by Django 4.2.7 on 2023-11-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_image_remove_signal_record_video_delete_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='count_persons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='helmet',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='person',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='warning',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Signal_record',
        ),
    ]
