# Generated by Django 4.2.7 on 2023-11-11 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_image_count_persons_image_helmet_image_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='helmet',
            new_name='seg_warning',
        ),
    ]
